apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ads-js
  annotations:
    github.com/project-slug: vtex/ads-js
    vtex.com/application-id: T8O9XHQS
spec:
  type: tool
  lifecycle: production
  owner: te-0059
