- name: ads-js
  referenceId: T8O9XHQS
  build:
    provider: dkcicd
    pipelines:
      - name: npm-publish-v1
        parameters:
          nodeVersion: "24-bookworm"
          packageManager: pnpm
          skipInstall: false
          nodeCommands:
            - build
          publishViaGithubWorkflow: true
          workflowFile: publish-npm.yml
          workflowVersion: "{{ ref_name }}"
        when:
          - event: push
            source: tag
            regex: ^(ads-core|ads-react)-v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$
